#############################################################################
# riders

## The following Netlify configurration is for the riders application ONLY
## In situations where multiple sites need to be deployed from a monorepo,
## Netlify configuration should be managed directly via the UI
#############################################################################

## -- BUILD -- ##

[build]
command = "npx nx build riders --skip-nx-cache && npx nx server:netlify riders --skip-nx-cache"
publish = "apps/riders/dist/public"

[build.environment]
PROJECT_NAME = "riders"

## - PROXY & CACHE -- ##

[[redirects]]
from = "/*"
status = 200
to = "/.netlify/functions/server"

# Favicon
[[headers]]
for = "/favicon.ico"
[headers.values]
"Cache-Control" = "public, max-age=5600"

# Images, Icons, etc.
[[headers]]
for = "/assets/*"
[headers.values]
"Cache-Control" = "public, max-age=5600"

# Remix
[[headers]]
for = "/build/*"
[headers.values]
"Cache-Control" = "public, max-age=60, s-maxage=60"

## -- FUNCTIONS -- ##

[functions]
directory = "apps/riders/dist/netlify"
external_node_modules = [
  "@remix-run/react",
  "@remix-run/node",
  "firebase-admin",
  "firebase",
  "mercadopago",
  "@mercadopago/sdk-js",
  "isbot",
  "remix-typedjson",
  "tslog",
  "react-prismazoom",
  "node-ts-cache",
  "node-ts-cache-storage-memory",
  "lodash",
  "@uniformdev/canvas",
  "@uniformdev/canvas-react",
  "@uniformdev/context-remix",
  "@reduxjs/toolkit",
  "formik",
  "ramda",
  "ramda-adjunct",
  "react-redux",
  "yup",
  "axios",
  "classnames",
]
included_files = ["apps/riders/dist/index.js", "apps/riders/data/**", "apps/riders/config/*.json"]
node_bundler = "esbuild"

## -- PLUGINS -- ##

#[[plugins]]
#package = "./tools/plugins/netlify/affected-build"
