export enum ProductUrlSeoConfig {
  PRODUCT_NAME = 'PRODUCT_NAME',
  PRODUCT_SLUG = 'PRODUCT_SLUG',
  PRODUCT_ID = 'PRODUCT_ID',
  CATEGORY_NAME = 'CATEGORY_NAME',
  CATEGORY_PATH_NAME = 'CATEGORY_PATH_NAME',
  CATEGORY_SLUG = 'CATEGORY_SLUG',
  CATEGORY_PATH_SLUG = 'CATEGORY_PATH_SLUG',
}
