export enum CategoryUrlSeoConfig {
  CATEGORY_PATH_SLUG = 'CATEGORY_PATH_SLUG',
  CATEGORY_SLUG = 'CATEGORY_SLUG',
  CATEGORY_PATH_NAME = 'CATEGORY_PATH_NAME',
  CATEGORY_NAME = 'CATEGORY_NAME',
  CATEGORY_PATH_ID = 'CATEGORY_PATH_ID',
  CATEGORY_ID = 'CATEGORY_ID',
}

export enum CategoryPathAttribute {
  NAME = 'NAME',
  SLUG = 'SLUG',
  ID = 'ID',
}
