import type { State } from '@ducati/types';

import {
  CA_AB,
  CA_BC,
  CA_MB,
  CA_NB,
  CA_NL,
  CA_NS,
  CA_NT,
  CA_NU,
  CA_ON,
  CA_PE,
  CA_QC,
  CA_SK,
  CA_YT,
  US_AK,
  US_AL,
  US_AR,
  US_AZ,
  US_CA,
  US_CO,
  US_CT,
  US_DE,
  US_FL,
  US_GA,
  US_HI,
  US_IA,
  US_ID,
  US_IL,
  US_IN,
  US_KS,
  US_KY,
  US_LA,
  US_MA,
  US_MD,
  US_ME,
  US_MI,
  US_MN,
  US_MO,
  US_MS,
  US_MT,
  US_NC,
  US_ND,
  US_NE,
  US_NH,
  US_NJ,
  US_NM,
  US_NV,
  US_NY,
  US_OH,
  US_OK,
  US_OR,
  US_PA,
  US_RI,
  US_SC,
  US_SD,
  US_TN,
  US_TX,
  US_UT,
  US_VA,
  US_VT,
  US_WA,
  US_WI,
  US_WV,
  US_WY,
} from './index';

export const STATES_CA: Map<string, State> = new Map<string, State>([
  [CA_NL.isocode, CA_NL],
  [CA_PE.isocode, CA_PE],
  [CA_NS.isocode, CA_NS],
  [CA_NB.isocode, CA_NB],
  [CA_QC.isocode, CA_QC],
  [CA_ON.isocode, CA_ON],
  [CA_MB.isocode, CA_MB],
  [CA_SK.isocode, CA_SK],
  [CA_AB.isocode, CA_AB],
  [CA_BC.isocode, CA_BC],
  [CA_YT.isocode, CA_YT],
  [CA_NT.isocode, CA_NT],
  [CA_NU.isocode, CA_NU],
]);

export const STATES_US: Map<string, State> = new Map<string, State>([
  [US_AL.isocode, US_AL],
  [US_AK.isocode, US_AK],
  [US_AZ.isocode, US_AZ],
  [US_AR.isocode, US_AR],
  [US_CA.isocode, US_CA],
  [US_CO.isocode, US_CO],
  [US_CT.isocode, US_CT],
  [US_DE.isocode, US_DE],
  [US_FL.isocode, US_FL],
  [US_GA.isocode, US_GA],
  [US_HI.isocode, US_HI],
  [US_ID.isocode, US_ID],
  [US_IL.isocode, US_IL],
  [US_IN.isocode, US_IN],
  [US_IA.isocode, US_IA],
  [US_KS.isocode, US_KS],
  [US_KY.isocode, US_KY],
  [US_LA.isocode, US_LA],
  [US_ME.isocode, US_ME],
  [US_MD.isocode, US_MD],
  [US_MA.isocode, US_MA],
  [US_MI.isocode, US_MI],
  [US_MN.isocode, US_MN],
  [US_MS.isocode, US_MS],
  [US_MO.isocode, US_MO],
  [US_MT.isocode, US_MT],
  [US_NE.isocode, US_NE],
  [US_NV.isocode, US_NV],
  [US_NH.isocode, US_NH],
  [US_NJ.isocode, US_NJ],
  [US_NM.isocode, US_NM],
  [US_NY.isocode, US_NY],
  [US_NC.isocode, US_NC],
  [US_ND.isocode, US_ND],
  [US_OH.isocode, US_OH],
  [US_OK.isocode, US_OK],
  [US_OR.isocode, US_OR],
  [US_PA.isocode, US_PA],
  [US_RI.isocode, US_RI],
  [US_SC.isocode, US_SC],
  [US_SD.isocode, US_SD],
  [US_TN.isocode, US_TN],
  [US_TX.isocode, US_TX],
  [US_UT.isocode, US_UT],
  [US_VT.isocode, US_VT],
  [US_VA.isocode, US_VA],
  [US_WA.isocode, US_WA],
  [US_WV.isocode, US_WV],
  [US_WI.isocode, US_WI],
  [US_WY.isocode, US_WY],
]);
